- name: longhorn prereqs
  hosts: all
  become: true
  become_user: root
  tasks:
  - name: install packages
    ansible.builtin.apt:
      name:
      - open-iscsi
      - nfs-common
      - bash
      - curl
      # provided buy util-linux: findmnt, blkid, lsblk
      - util-linux
      - grep
      - gawk
      update_cache: yes

  - name: iscsi tcp module
    community.general.modprobe:
      name: iscsi_tcp
      state: present
      persistent: present

  # Longhorn(?) is not happy without some huge number of open files and gives errors like this:
  #   failed to create fsnotify watcher: too many open files
  # https://serverfault.com/questions/1137211/failed-to-create-fsnotify-watcher-too-many-open-files
  # - thanks Steven!
  - name: increase fs.notify.max.user_watches
    ansible.posix.sysctl:
      name: fs.inotify.max_user_watches
      value: '2099999999'
      state: present
  - name: increase fs.inotify.max_user_instances
    ansible.posix.sysctl:
      name: fs.inotify.max_user_instances
      value: '2099999999'
      state: present
  - name: increase fs.inotify.max_queued_events
    ansible.posix.sysctl:
      name: fs.inotify.max_queued_events
      value: '2099999999'
      state: present
