- name: longhorn prereqs
  hosts: all
  become: true
  become_user: root
  tasks:
  - name: install packages
    ansible.builtin.apt:
      name:
      - open-iscsi
      - nfs-common
      - bash
      - curl
      # provided buy util-linux: findmnt, blkid, lsblk
      - util-linux
      - grep
      - gawk

      # not longhorn just for funsies
      - bmon
      - ipvsadm
      - tcpdump
      - arping
      - ceph-osd
      update_cache: yes

  - name: kmod - iscsi_tcp
    community.general.modprobe:
      name: iscsi_tcp
      state: present
      persistent: present

  - name: kmod - uio
    community.general.modprobe:
      name: uio
      state: present
      persistent: present

  - name: kmod - uio_pci_generic
    community.general.modprobe:
      name: uio_pci_generic
      state: present
      persistent: present

  - name: kmod - nvme-tcp``
    community.general.modprobe:
      name: nvme-tcp
      state: present
      persistent: present

  # Longhorn(?) is not happy without some huge number of open files and gives errors like this:
  #   failed to create fsnotify watcher: too many open files
  # https://serverfault.com/questions/1137211/failed-to-create-fsnotify-watcher-too-many-open-files
  # - thanks Steven!
  - name: sysctl - fs.notify.max.user_watches
    ansible.posix.sysctl:
      name: fs.inotify.max_user_watches
      value: '2099999999'
      state: present
  - name: sysctl - fs.inotify.max_user_instances
    ansible.posix.sysctl:
      name: fs.inotify.max_user_instances
      value: '2099999999'
      state: present
  - name: sysctl - fs.inotify.max_queued_events
    ansible.posix.sysctl:
      name: fs.inotify.max_queued_events
      value: '2099999999'
      state: present
  - name: sysctl - vm.nr_hugepages
    ansible.posix.sysctl:
      name: vm.nr_hugepages
      value: "1024"
      state: present
