- name: registries
  hosts: all
  become: true
  become_user: root
  tasks:

  - ansible.builtin.file:
      path: /etc/rancher/k3s/
      state: directory
      owner: root
      group: root
      mode: "0700"

  - name: registries.yaml
    ansible.builtin.copy:
      src: ../registries.yaml
      dest: /etc/rancher/k3s/registries.yaml
      owner: root
      group: root
      mode: '0600'

  - name: ca.pem
    ansible.builtin.copy:
      src: ~/ca/ca.pem
      dest: /etc/rancher/k3s/ca.pem
      owner: root
      group: root
      mode: '0600'

  # k3s service on servers: "k3s"
  # k3s service on agents: "k3s-agent"
  - name: k3s
    ansible.builtin.systemd_service:
      state: restarted
      name: "{{ ('server' in group_names)|ternary('k3s', 'k3s-agent') }}"