---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: longhorn
  namespace: istio-ingress
spec:
  hosts:
  - 'longhorn.lan.asio'
  gateways:
  - gateway
  http:
  - route:
    - destination:
        host: longhorn-frontend.longhorn-system.svc.cluster.local
        port:
          number: 80
