apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-advertisement
  namespace: metallb-system
# example of how to attach services to just one host
# spec:
#   ipAddressPools:
#   - default
#   nodeSelectors:
#   - matchLabels:
#       kubernetes.io/hostname: k3s-prod-server-0.lan.asio
