apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  # Address pool MetalLB will allocate from, adjust your router to not
  # allocate address in this range to prevent clash
  # - 172.20.1.100-172.20.1.250
  - 10.50.1.100-10.50.1.250
