service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.3.8
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP

