apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-advertisement
  namespace: metallb-system
spec:
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: cloud.lan.asio

